### ISSUE TITLE
小米Mix2s 选择图片时，一些图片路径不存在。

### ISSUE THREAD

**Issue by sky-lijinbo** [REBOOTERS/Matisse#4]
小米Mix 2s ，Android 10, MIUI版本 12.5.1

进入Matisse 图片选择页面，Pictures/ 路径下， WeiXin 或 Aplipay 文件夹下，个别图片展示不出来，选择返回后，查看路径，该路径下不存在此图片文件。

**Comment by REBOOTERS** [comment]
> 小米Mix 2s ，Android 10, MIUI版本 12.5.1
> 
> 进入Matisse 图片选择页面，Pictures/ 路径下， WeiXin 或 Aplipay 文件夹下，个别图片展示不出来，选择返回后，查看路径，该路径下不存在此图片文件。

是特殊的图片格式吗？
